Create the `bookrecommendation` microservice:

`mn create-app example.micronaut.bookrecommendation.bookrecommendation`

The previous command creates a folder named `bookrecommendation` and a Micronaut app inside it with
default package: `example.micronaut.bookrecommendation`.

Modify `build.gradle` to add `rabbitmq` dependency. In this microservice we will use Micronaut HTTP Server to receive
REST request so it is not necessary to remove any dependency.

[source,java]
.bookrecommendation/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookrecommendation/build.gradle[tag=rabbitmq]
}
----

=== Create RabbitMQ exchange, queue and binding

As we did in `Catalogue` Microservice, create the class `ChannelPoolListener.java` in `bookrecommendation/src/main/java/example/micronaut/bookcatalogue/ChannelPoolListener.java`
with the same content as before.


=== Create clients

Let's create two interfaces to send messages to RabbitMQ. Micronaut will implement the interfaces at compilation time.
Create `CatalogueClient.java`:

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookinventory/CatalogueClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/CatalogueClient.java[]
----
<1> Send the messages to exchange `micronaut`.
<2> Set the `replyTo` property to `amq.rabbitmq.reply-to`. This is a special queue that always exists and does not need
to be created. That it is why we did not create the queue in the `ChannelInitializer`. RabbitMQ uses that queue in a
special way and setting the value of the property `replyTo` to that queue will enable this call as a RPC one. RabbitMQ
will create a temporary queue for the callback.
<3> Set the routing key.
<4> Define the method that will "mirror" the one in the consumer. Keep in mind that in the consumer it is not possible to
return a reactive type, but on the client side it is. Also, it is necessary to send something, even if it's not
used in the consumer.


Create `InventoryClient.java`:

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookinventory/InventoryClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/InventoryClient.java[]
----
<1> Send the messages to exchange `micronaut`.
<2> Set the `replyTo` property to `amq.rabbitmq.reply-to`.
<3> Set the routing key.
<4> Define the method that will "mirror" the one in the consumer. As we did with `CatalogueClient` we use a reactive
type to wrap the result.


=== Create the controller

Create a Controller which injects both clients.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/books`
<2> Clients are injected via constructor injection
<3> The `@Get` annotation is used to map the index method to an HTTP GET request on `/books`.


The previous controller returns a `Flowable<BookRecommendation>`. Create the `BookRecommendation` POJO:

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookRecommendation.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookRecommendation.java[]
----
